SonarSource/sonarqube-webclient-dotnet

- SonarQube.Client.Tests/SonarQubeService_GetAllOrganizationsAsync.cs
- SonarQube.Client/Api/V7_00/GetOrganizationsRequest.cs
> Limit organization search to own organizations

- SonarQube.Client.Tests/SonarQubeService_TestBase.cs
Fix for https://github.com/SonarSource/sonarlint-visualstudio/issues/902
> Fix unit tests in non-English locale

- SonarQube.Client.Tests/SonarQubeService_HasOrganizations.cs
- SonarQube.Client.Tests/SonarQubeService_TestBase.cs
- SonarQube.Client/Models/ConnectionInformation.cs
- SonarQube.Client/SonarQubeService.cs
> Changed HasOrganizations to not use api/organizations/search

- SonarQube.Client.Tests/Helpers/AuthenticationHeaderFactoryTests.cs
- SonarQube.Client.Tests/Helpers/QueryStringSerializerTests.cs
- SonarQube.Client.Tests/Requests/RequestFactoryTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetAllModulesAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetProjectDashboardUrl.cs
- SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
- SonarQube.Client.Tests/SonarQubeService_HasOrganizations.cs
- SonarQube.Client.Tests/SonarQubeService_PagedRequestTests.cs
> Test cleanup - fixed Fluent assertion issues

- SonarQube.Client.Tests/SonarQubeService_ExtensionMethods.cs
- SonarQube.Client/ServiceExtensions.cs
Get all rules, active and inactive
> Added extension method to get all rules for QP

- SonarQube.Client.Tests/SonarQubeService_ExtensionMethods.cs
- SonarQube.Client.Tests/SonarQubeService_TestBase.cs
- SonarQube.Client/ServiceExtensions.cs
* tests for no active/inactive rules and exceptions in ext method
> Added more tests for GetRulesAsync

- SonarQube.Client/SonarQube.Client.csproj
> Reverted version to System.Net.Http used

- SonarQube.Client.Tests/SonarQubeService_GetRulesAsync.cs
- SonarQube.Client/Api/V5_50/GetRulesRequest.cs
- SonarQube.Client/Models/SonarQubeRule.cs
> GetRulesAsync uses singleton for empty parameters

- LICENSE
- NOTICE.txt
- SonarQube.Client.Tests/Properties/AssemblyInfo.cs
- SonarQube.Client/Messages/Protobuf/constants.proto
- SonarQube.Client/Messages/Protobuf/scanner_input.proto
- SonarQube.Client/Properties/AssemblyInfo.cs
> Update remaining license headers for 2020

- SonarQube.Client/SonarQube.Client.csproj
> Use SLVS shared assembly properties when building in SLVS

- SonarQube.Client.Tests/RoslynExporterAdapter/RoslynRuleSetGeneratorTests.cs
- SonarQube.Client/RoslynExporterAdapter/RoslynRuleSetGenerator.cs
- SonarQube.Client/RoslynExporterAdapter/RuleAction.cs
- SonarQube.Client/RoslynExporterAdapter/RuleSet.cs
> Added ruleset generator code and tests copied from S4MSB

- SonarQube.Client.Tests/RoslynExporterAdapter/NuGetPackageInfoGeneratorTests.cs
- SonarQube.Client.Tests/RoslynExporterAdapter/RoslynPluginRuleKeyExtensionsTests.cs
- SonarQube.Client/RoslynExporterAdapter/NuGetPackageInfoGenerator.cs
- SonarQube.Client/RoslynExporterAdapter/RoslynPluginRuleKeyExtensions.cs
Adds a generator for the NuGetPackageInfo part of the RoslynExporter response.
> Added NuGePackageInfoGenerator

- SonarQube.Client.Tests/Helpers/SonarQubeIssueTypeConverterTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetRulesAsync.cs
- SonarQube.Client/Api/V5_50/GetRulesRequest.cs
- SonarQube.Client/Models/SonarQubeIssueType.cs
- SonarQube.Client/Models/SonarQubeRule.cs
Required by SLVS to filter out hotspots.
> Added issue type to SonarQubeRule

- SonarQube.Client.Tests/SonarQube.Client.Tests.csproj
- SonarQube.Client.Tests/SonarQubeService_GetAllProjectsAsync.cs
- SonarQube.Client.Tests/SonarQubeService_PagedRequestTests.cs
- SonarQube.Client/Api/V2_10/GetProjectsRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequestWrapper.cs
- SonarQube.Client/Requests/IPagedRequest.cs
- SonarQube.Client/Requests/PagedRequestBase.cs
- SonarQube.Client/SonarQubeService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/1292
Fixes #8
> Fix paging to avoid error when reaching 10k API limit

- SonarQube.Client.Tests/SonarQubeService_GetQualityProfileAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
- SonarQube.Client/Requests/PagedRequestBase.cs
> Fixed incorrectly-displayed "max items retrieved" message

- SonarQube.Client.Tests/Infra/MocksHelper.cs
- SonarQube.Client.Tests/Models/IssueFlowTests.cs
- SonarQube.Client.Tests/Models/SonarQubeIssueTests.cs
- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetAllModulesAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetNotificationEventsAsync.cs
- SonarQube.Client.Tests/SonarQubeService_Lifecycle.cs
- SonarQube.Client.Tests/SonarQubeService_PagedRequestTests.cs
- SonarQube.Client.Tests/SonarQubeService_TestBase.cs
- SonarQube.Client/Api/V5_10/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Models/SonarQubeIssue.cs
> Added flow information to SonarQubeIssue

- SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
- SonarQube.Client.Tests/SonarQubeService_GetHotspotAsync.cs
- SonarQube.Client/Api/DefaultConfiguration.cs
- SonarQube.Client/Api/IGetHotspotRequest.cs
- SonarQube.Client/Api/V8_1/GetHotspotRequest.cs
- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/Models/SonarQubeHotspot.cs
- SonarQube.Client/SonarQubeService.cs
Relates to https://github.com/SonarSource/sonarlint-visualstudio/issues/1771
> Added GetHotspot method to API

- SonarQube.Client.Tests/SonarQubeService_GetHotspotAsync.cs
- SonarQube.Client/Api/V8_1/GetHotspotRequest.cs
- SonarQube.Client/Models/SonarQubeHotspot.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/1858
> Add TextRange to hotspots

- SonarQube.Client.Tests/Helpers/FilePathNormalizerTests.cs
- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetHotspotAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
- SonarQube.Client/Api/V5_10/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Api/V8_1/GetHotspotRequest.cs
- SonarQube.Client/Helpers/FilePathNormalizer.cs
- SonarQube.Client/Models/SonarQubeHotspot.cs
- SonarQube.Client/Models/SonarQubeIssue.cs
Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/1763
> Normalize hotspot and issue file paths

- SonarQube.Client.Tests/SonarQubeService_GetAllModulesAsync.cs
- SonarQube.Client/Api/V5_40/GetModulesRequest.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/1891
> Normalize module path

- SonarQube.Client/Helpers/FilePathNormalizer.cs
- SonarQube.Client/Models/SonarQubeHotspot.cs
- SonarQube.Client/Models/SonarQubeIssue.cs
> Added doc comments / copyright notices

- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestTests.cs
- SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/DefaultConfiguration.cs
- SonarQube.Client/Api/IGetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/SonarQubeService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/1990
> Fetch taint vulnerabilities

- SonarQube.Client.Tests/Models/SonarQubeIssueTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/V5_10/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Models/SonarQubeIssue.cs
Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/1988
> Add Severity and TextRange fields to SonarQubeIssue

- SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/DefaultConfiguration.cs
- SonarQube.Client/Api/V8_6/GetTaintVulnerabilitiesRequest.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/2016
> Restrict GetTaintVulnerabilities to v8.6+

- SonarQube.Client.Tests/Models/ConnectionInformationTests.cs
- SonarQube.Client.Tests/SonarQubeService_Lifecycle.cs
- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/Models/ConnectionInformation.cs
- SonarQube.Client/SonarQubeService.cs
> Added IsSonarCloud property

- SonarQube.Client.Tests/Models/SonarQubeIssueTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/V5_10/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Models/SonarQubeIssue.cs
> Added required fields to SonarQubeIssue

- SonarQube.Client.Tests/SonarQubeService_GetHotspotAsync.cs
- SonarQube.Client/Api/V8_6/GetHotspotRequest.cs
- SonarQube.Client/Models/SonarQubeHotspot.cs
* maintains parity with common data returned in SonarQubeIssue
> Added creation and update date to SonarQubeHotspot

- SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
- SonarQube.Client.Tests/Requests/RequestFactorySelectorTests.cs
- SonarQube.Client.Tests/Requests/UnversionedRequestFactoryTests.cs
- SonarQube.Client/Api/DefaultConfiguration.cs
- SonarQube.Client/Requests/IRequestFactorySelector.cs
- SonarQube.Client/Requests/UnversionedRequestFactory.cs
Added unversioned request factory
Added configuration for SonarCloud
Relates to #80
> Added unversioned request factory

- SonarQube.Client.Tests/Requests/RequestFactorySelectorTests.cs
- SonarQube.Client/Requests/IRequestFactorySelector.cs
> Added SonarCloud request factory

- SonarQube.Client.Tests/ChecksumCalculatorTests.cs
- SonarQube.Client/ChecksumCalculator.cs
- SonarQube.Client/SonarQube.Client.csproj
> Moved checksum calculator from SLVS to client library

- SonarQube.Client.Tests/CallRealServerTestHarness.cs
- SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
- SonarQube.Client.Tests/SonarQubeService_GetSourceCodeAsync.cs
- SonarQube.Client/Api/DefaultConfiguration.cs
- SonarQube.Client/Api/IGetSourceCode.cs
- SonarQube.Client/Api/IGetSourceCodeRequest.cs
- SonarQube.Client/Api/V5_00/GetSourceCodeRequest.cs
- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/SonarQubeService.cs
> Added GetSourceCode API

- SonarQube.Client.Tests/Helpers/SecondaryIssueHashUpdaterTests.cs
- SonarQube.Client/Helpers/SecondaryIssueHashUpdater.cs
- SonarQube.Client/Models/SonarQubeIssue.cs
> Added secondary location hash updater

- SonarQube.Client.Tests/SonarQubeService_Miscellaneous.cs
- SonarQube.Client.Tests/SonarQubeService_TestBase.cs
- SonarQube.Client/SonarQubeService.cs
Removed tests of test-only constructor
> Minor cleanup - moved test-only params to end of param list

- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client.Tests/SonarQubeService_Miscellaneous.cs
- SonarQube.Client.Tests/SonarQubeService_TestBase.cs
- SonarQube.Client/Helpers/SecondaryLocationHashUpdater.cs
- SonarQube.Client/SonarQubeService.cs
Fixes #89
Related to https://github.com/SonarSource/sonarlint-visualstudio/issues/1762
> Modified taint API to populate secondary location issues

- SonarQube.Client.Tests/SonarQubeService_Lifecycle.cs
- SonarQube.Client/SonarQubeService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/2406
> Set IsConnected to false if ConnectAsync fails

- Directory.Build.props
- SonarQube.Client.Tests/SonarQube.Client.Tests.csproj
- SonarQube.Client.sln
- SonarQube.Client/SonarQube.Client.csproj
Done so the version can be set in a single place.
Similar changes will be made in the SLVS repo.
> Centralise Newtonsoft.Json package reference

- SonarQube.Client.Tests/SonarQubeService_GetProjectDashboardUrl.cs
- SonarQube.Client/SonarQubeService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/2753
> Fix SC dashboard URL

- SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Properties/AssemblyInfo.cs
Fixes [SLVS-2941](https://github.com/SonarSource/sonarlint-visualstudio/issues/2941)
> [GetIssues] Stop stripping repo prefix

- SonarQube.Client.Tests/Requests/Api/V7_20/GetExclusionsRequestTests.cs
- SonarQube.Client.Tests/SonarQube.Client.Tests.csproj
- SonarQube.Client/Api/IGetExclusionsRequest.cs
- SonarQube.Client/Api/V7_20/GetExclusionsRequest.cs
- SonarQube.Client/Models/ServerExclusions.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3042
> Add API endpoint to Web Client to fetch the exclusions

- SonarQube.Client.Tests/Requests/Api/V7_20/GetExclusionsRequestTests.cs
- SonarQube.Client.Tests/SonarQubeService_GetExclusionsRequest.cs
- SonarQube.Client/Api/V7_20/GetExclusionsRequest.cs
- SonarQube.Client/Models/ServerExclusions.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3062
> Remove global inclusions field

- SonarQube.Client/Models/ServerExclusions.cs
Fixes [#3077](https://github.com/SonarSource/sonarlint-visualstudio/issues/3077), prep for [#3078](https://github.com/SonarSource/sonarlint-visualstudio/issues/3078)
> Add serialization properties and ToString for logs

- SonarQube.Client/SonarQubeService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/696
> Mark service as Connected only after full initialization

- SonarQube.Client.Tests/Infra/MocksHelper.cs
- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestTests.cs
- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestWrapperTests.cs
- SonarQube.Client/Api/IGetIssuesRequest.cs
- SonarQube.Client/Api/V5_10/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequestWrapper.cs
> Add branch parameter to GetIssuesAsync

- SonarQube.Client.Tests/Infra/MocksHelper.cs
- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/IGetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/Api/V8_6/GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/SonarQubeService.cs
> Add optional branch parameter to GetTaintVulnerabilitiesRequest

- SonarQube.Client/Api/V2_10/GetPluginsRequest.cs
- SonarQube.Client/Api/V2_10/GetProjectsRequest.cs
- SonarQube.Client/Api/V2_60/GetPropertiesRequest.cs
- SonarQube.Client/Api/V5_10/GetLanguagesRequest.cs
- SonarQube.Client/Api/V5_20/GetQualityProfileChangeLogRequest.cs
- SonarQube.Client/Api/V5_20/GetQualityProfilesRequest.cs
- SonarQube.Client/Api/V5_40/GetModulesRequest.cs
- SonarQube.Client/Api/V5_50/GetRulesRequest.cs
- SonarQube.Client/Api/V6_20/GetOrganizationsRequest.cs
- SonarQube.Client/Api/V6_20/GetProjectsRequest.cs
- SonarQube.Client/Api/V6_30/GetPluginsRequest.cs
- SonarQube.Client/Api/V6_30/GetPropertiesRequest.cs
- SonarQube.Client/Api/V6_60/GetNotificationsRequest.cs
- SonarQube.Client/Api/V6_60/GetProjectBranchesRequest.cs
- SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
- SonarQube.Client/Api/V8_6/GetHotspotRequest.cs
- SonarQube.Client/Helpers/SecondaryLocationHashUpdater.cs
- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/Models/ConnectionInformation.cs
- SonarQube.Client/SonarQubeService.cs
Minor changes to product code.
No functional impact.
> Cleanup - product code

- SonarQube.Client.Tests/AssertIgnoreScope.cs
- SonarQube.Client.Tests/Helpers/QueryStringSerializerTests.cs
- SonarQube.Client.Tests/Models/ConnectionInformationTests.cs
- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestTests.cs
- SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestWrapperTests.cs
- SonarQube.Client.Tests/SonarQubeService_ExtensionMethods.cs
- SonarQube.Client.Tests/SonarQubeService_GetProjectBranchesAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
- SonarQube.Client.Tests/SonarQubeService_HasOrganizations.cs
Minor changes to test code.
No changes to product code.
> Cleanup - test code

- SonarQube.Client/ISonarQubeService.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/IIssueChangedServerEvent.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/IServerEvent.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintServerEvent.cs
- SonarQube.Client/Models/ServerSentEvents/IServerSentEventsSession.cs
- SonarQube.Client/Models/ServerSentEvents/ServerContract/IIssueChangedSqServerEvent.cs
- SonarQube.Client/Models/ServerSentEvents/ServerContract/ISqServerEvent.cs
- SonarQube.Client/Models/ServerSentEvents/ServerContract/ITaintVulnerabilityClosedSqServerEvent.cs
- SonarQube.Client/Models/ServerSentEvents/ServerContract/ITaintVulnerabilityRaisedSqServerEvent.cs
- SonarQube.Client/SonarQubeService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3530
> Add initial interfaces

- SonarQube.Client.Tests/SonarQube.Client.Tests.csproj
- SonarQube.Client.Tests/SonarQubeService_GetNotificationEventsAsync.cs
- SonarQube.Client.Tests/SonarQubeService_GetSourceCodeAsync.cs
- SonarQube.Client.Tests/packages.lock.json
- SonarQube.Client/SonarQube.Client.csproj
- SonarQube.Client/packages.lock.json
Prep for using channels nuget package
> Update .net framework to 472

- SonarQube.Client.Tests/SonarQube.Client.Tests.csproj
- SonarQube.Client.Tests/packages.lock.json
Fixes https://github.com/SonarSource/sonarqube-webclient-dotnet/issues/149
> Update Moq to 4.18.2

- SonarQube.Client.Tests/Models/ServerSentEvents/TaintVulnerabilityRaisedServerEventTests.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintIssue.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintServerEvent.cs
Prep for [#3676](https://github.com/SonarSource/sonarlint-visualstudio/issues/3676)
> Add issueKey to ITaintIssue

- SonarQube.Client.Tests/Helpers/MillisecondUnixTimestampDateTimeOffsetConverterTests.cs
- SonarQube.Client.Tests/Models/ServerSentEvents/SSEStreamReaderTests.cs
- SonarQube.Client.Tests/Models/ServerSentEvents/TaintVulnerabilityRaisedServerEventTests.cs
- SonarQube.Client/Helpers/MillisecondUnixTimestampDateTimeOffsetConverter.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintIssue.cs
- SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintServerEvent.cs
Closes https://github.com/SonarSource/sonarlint-visualstudio/issues/3706
> Deserialize CreationDate for TaintRaised
